# These are supported funding model platforms

github: ikegami-yukino
custom: ['https://www.amazon.co.jp/hz/wishlist/ls/15HRUQ0OYGJYQ?type=wishlist&filter=unpurchased&sort=priority', 'https://www.soundhouse.co.jp/customers/wishlist/index/?list_id=85773']
